spring:
  application:
    name: CoworClean

  datasource:
    url: jdbc:postgresql://localhost:5432/coworclean
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    location: classpath:db/migration